spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shaden-test}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jakarta:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: true
logging:
  level:
    root: WARN
    "[org.springframework.security.web]": DEBUG
    "[org.springframework.boot.orm.jpa.hibernate]": ERROR
    "[com.example.shaden]": INFO

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: 900000
      refresh-token:
        expiration: 604800000
