spring:
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jakarta:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: true
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}

logging:
  level:
    root: WARN
    "[org.springframework.security.web]": DEBUG
    "[org.springframework.boot.orm.jpa.hibernate]": ERROR
    "[com.example.shaden]": INFO

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: ${ACCESS_TOKEN_EXPIRATION_TIME}
      refresh-token:
        expiration: ${REFRESH_TOKEN_EXPIRATION_TIME}
  frontend:
    web-app-url: ${FRONTEND_WEB_APP_URL}
    landing-page-url: ${FRONTEND_LANDING_PAGE_URL}
